#cloud-config
# Example ARM64 storage configuration with explicit EFI partition
# Use this if you need more control over partitioning on ARM64 systems

autoinstall:
  version: 1
  
  storage:
    config:
      # Main disk
      - type: disk
        id: disk0
        ptable: gpt
        path: /dev/sda  # Adjust based on your virtualization platform
        wipe: superblock-recursive
        preserve: false
        grub_device: false
      
      # EFI System Partition (required for ARM64)
      - type: partition
        id: partition-efi
        device: disk0
        size: 512M
        flag: boot
        number: 1
        preserve: false
        grub_device: true
      
      - type: format
        id: format-efi
        volume: partition-efi
        fstype: fat32
        label: ESP
      
      - type: mount
        id: mount-efi
        device: format-efi
        path: /boot/efi
      
      # Boot partition (optional but recommended)
      - type: partition
        id: partition-boot
        device: disk0
        size: 1G
        number: 2
        preserve: false
      
      - type: format
        id: format-boot
        volume: partition-boot
        fstype: ext4
        label: BOOT
      
      - type: mount
        id: mount-boot
        device: format-boot
        path: /boot
      
      # LVM partition for the rest
      - type: partition
        id: partition-lvm
        device: disk0
        size: -1  # Use remaining space
        number: 3
        preserve: false
      
      - type: lvm_volgroup
        id: vg0
        name: ubuntu-vg
        devices:
          - partition-lvm
      
      # Root logical volume
      - type: lvm_partition
        id: lv-root
        name: ubuntu-lv
        volgroup: vg0
        size: 20G  # Adjust as needed
      
      - type: format
        id: format-root
        volume: lv-root
        fstype: ext4
        label: ROOT
      
      - type: mount
        id: mount-root
        device: format-root
        path: /
      
      # Swap logical volume (optional)
      - type: lvm_partition
        id: lv-swap
        name: swap-lv
        volgroup: vg0
        size: 2G
      
      - type: format
        id: format-swap
        volume: lv-swap
        fstype: swap
        label: SWAP
      
      - type: mount
        id: mount-swap
        device: format-swap
        path: none